export enum ZoneType {
  STANDARD = 'STANDARD',
  RESTRICTED = 'RESTRICTED',
  HAZARDOUS = 'HAZARDOUS',
}

export enum ZoneRestrictionPolicy {
  NONE = 'NONE',
  PROHIBITED_FOR_ALL = 'PROHIBITED_FOR_ALL',
  AUTHORIZATION_REQUIRED = 'AUTHORIZATION_REQUIRED',
}

export enum CameraStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum EventProcessingStatus {
  PROCESSED = 'PROCESSED',
  SKIPPED_CLOCK_SKEW = 'SKIPPED_CLOCK_SKEW',
  SKIPPED_NO_CANDIDATE = 'SKIPPED_NO_CANDIDATE',
  SKIPPED_UNKNOWN_CAMERA = 'SKIPPED_UNKNOWN_CAMERA',
}

export enum AlertType {
  PPE_VIOLATION = 'PPE_VIOLATION',
  RESTRICTED_ZONE_INTRUSION = 'RESTRICTED_ZONE_INTRUSION',
}

export enum AlertStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_MORE_EVIDENCE = 'NEEDS_MORE_EVIDENCE',
  CONFIRMED = 'CONFIRMED',
  DISMISSED = 'DISMISSED',
  CLOSED = 'CLOSED',
}
