export enum ZoneType {
  STANDARD = 'STANDARD',
  RESTRICTED = 'RESTRICTED',
  HAZARDOUS = 'HAZARDOUS',
}

export enum ZoneRestrictionPolicy {
  NONE = 'NONE',
  PROHIBITED_FOR_ALL = 'PROHIBITED_FOR_ALL',
  AUTHORIZATION_REQUIRED = 'AUTHORIZATION_REQUIRED',
}

export enum CameraStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum EventProcessingStatus {
  PROCESSED = 'PROCESSED',
  SKIPPED_CLOCK_SKEW = 'SKIPPED_CLOCK_SKEW',
  SKIPPED_NO_CANDIDATE = 'SKIPPED_NO_CANDIDATE',
  SKIPPED_UNKNOWN_CAMERA = 'SKIPPED_UNKNOWN_CAMERA',
}

export enum AlertType {
  PPE_VIOLATION = 'PPE_VIOLATION',
  RESTRICTED_ZONE_INTRUSION = 'RESTRICTED_ZONE_INTRUSION',
}

export enum AlertStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  NEEDS_MORE_EVIDENCE = 'NEEDS_MORE_EVIDENCE',
  CONFIRMED = 'CONFIRMED',
  DISMISSED = 'DISMISSED',
  CLOSED = 'CLOSED',
}

export enum AttendancePairStatus {
  MATCHED = 'MATCHED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  CALCULATED = 'CALCULATED',
  CORRECTED = 'CORRECTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AttendanceAnomalyCode {
  MISSING_IN = 'MISSING_IN',
  MISSING_OUT = 'MISSING_OUT',
  OUT_WITHOUT_IN = 'OUT_WITHOUT_IN',
  DUPLICATE_IN = 'DUPLICATE_IN',
  DUPLICATE_OUT = 'DUPLICATE_OUT',
  LATE_CHECKIN = 'LATE_CHECKIN',
  EARLY_CHECKOUT = 'EARLY_CHECKOUT',
  CROSS_MIDNIGHT = 'CROSS_MIDNIGHT',
}

export enum AttendanceCorrectionStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TimesheetStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ShiftRequestStatus {
  DRAFT = 'DRAFT',
  PENDING_COWORKER = 'PENDING_COWORKER',
  PENDING_MANAGER = 'PENDING_MANAGER',
  APPROVED = 'APPROVED',
  APPLIED = 'APPLIED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  CONFLICTED = 'CONFLICTED',
}

export enum AbsenceRequestStatus {
  PENDING_MANAGER = 'PENDING_MANAGER',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
